version: '3.8'

services:
  web:
    # Контекст: текущая папка (Quiz)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz_api
    restart: always
    ports:
      - '5000:8080' # Маппинг портов: 5000 на хосте -> 8080 в контейнере
    environment:
      # ВНИМАНИЕ: Пароль 'password' должен совпадать с паролем в сервисе 'db'
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=quizdb;Username=postgres;Password=password
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохранение данных
    ports:
      - '5432:5432'

volumes:
  postgres_data:
